name: run_latest_python

on:
  workflow_dispatch:

jobs:
  test_my_fork:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # enables push access
          persist-credentials: true

      - name: Set up latest Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.X'

      - name: Install dependencies
        run: |
          pip install pandas
          pip install numpy
          pip install git+https://github.com/svenbuder/AnniesLasso.git@master

      - name: Run test_cannon_andy_latest_python.py
        run: |
          python test_cannon_andy_latest_python.py

      - name: Commit and push generated files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add prospect_model_latest_python.model prospect_model_restricted_latest_python.model
          git commit -m "Auto-update models" || echo "No changes to commit"
          git push
